# permissions for end users to edit foos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: foo-controller-kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: foo-editor-role
rules:
- apiGroups:
  - samplecontroller.hagitech.net
  resources:
  - foos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - samplecontroller.hagitech.net
  resources:
  - foos/status
  verbs:
  - get
